/**
 * AdSense / EEAT content calendar — 15 authoritative educational articles.
 * Each entry maps to blogPosts.ts registry id and public URL slug.
 */
export type ContentCalendarEntry = {
  id: string;
  slug: string;
  primaryKeyword: string;
  metaTitle: string;
  metaDescription: string;
  eeatAngle: string;
  outline: { h2: string; h3?: string[] }[];
};

export const CONTENT_CALENDAR: ContentCalendarEntry[] = [
  {
    id: "remote-communication",
    slug: "improve-remote-team-communication",
    primaryKeyword: "improve remote team communication",
    metaTitle: "7 Ways to Improve Remote Team Communication (No Extra Meetings)",
    metaDescription:
      "Practical strategies for distributed teams to communicate clearly across time zones—without calendar overload.",
    eeatAngle:
      "Four-week internal experiment replacing 'quick sync' invites with async screen recordings; ~60% of meetings eliminated.",
    outline: [
      { h2: "Define Where Each Conversation Should Live", h3: ["Channel map template", "Incident vs decision vs status"] },
      { h2: "Write for Someone Who Missed the Last Three Threads", h3: ["Context → ask → deadline pattern"] },
      { h2: "Replace Status Meetings with Async Check-Ins" },
      { h2: "Record Walkthroughs When Text Fails" },
      { h2: "Set Response-Time Expectations That Respect Deep Work" },
      { h2: "Build a Shared Language for Urgency", h3: ["P0–P3 labeling system"] },
      { h2: "Review Communication Quarterly Like You Review Code" },
      { h2: "Our Real-World Experience at theRec" },
    ],
  },
  {
    id: "timezone-collaboration",
    slug: "collaborate-across-time-zones-without-burnout",
    primaryKeyword: "collaborate across time zones",
    metaTitle: "Collaborate Across Time Zones Without Team Burnout",
    metaDescription: "Overlap windows, async handoffs, and fair scheduling for 24/7 distributed teams.",
    eeatAngle: "Ninety-minute overlap policy experiment across two continents at theRec.",
    outline: [
      { h2: "Map Your Team's Real Working Hours" },
      { h2: "Protect a Small Overlap Window—Then Defend It" },
      { h2: "Build Handoff Rituals That Actually Transfer Context" },
      { h2: "Default to Async for Status, Sync for Ambiguity" },
      { h2: "Rotate the Inconvenience Fairly" },
      { h2: "Our Real-World Experience at theRec" },
    ],
  },
  {
    id: "meeting-fatigue",
    slug: "reduce-meeting-fatigue-remote-teams",
    primaryKeyword: "meeting fatigue remote teams",
    metaTitle: "6 Ways to Reduce Meeting Fatigue on Remote Teams",
    metaDescription: "Cut calendar clutter and protect focus time with proven remote team tactics.",
    eeatAngle: "Meeting diet quarter: eight-hour weekly internal meeting cap at theRec.",
    outline: [
      { h2: "Audit Your Calendar Like an Expense Report" },
      { h2: "Apply the Could-This-Be-a-Message Test" },
      { h2: "Institute Meeting-Free Blocks" },
      { h2: "Shrink Default Meeting Length" },
      { h2: "Require Agendas and Desired Outcomes" },
      { h2: "Measure Meetings Like You Measure Bugs" },
      { h2: "Our Real-World Experience at theRec" },
    ],
  },
  {
    id: "async-onboarding",
    slug: "async-onboarding-remote-hires",
    primaryKeyword: "async onboarding remote employees",
    metaTitle: "Async Onboarding: Welcome Remote Hires Without Meeting Overload",
    metaDescription: "Recorded walkthroughs and structured docs for scalable remote employee onboarding.",
    eeatAngle: "Contractor onboarded across six-hour TZ gap shipped feature on day four.",
    outline: [
      { h2: "Separate Must-Know Day One from Learn Over Time" },
      { h2: "Build a Recorded Library for Repeatable Walkthroughs" },
      { h2: "Assign a Human Anchor, Not Just a Buddy" },
      { h2: "Give New Hires a Single Onboarding Home Base" },
      { h2: "Schedule Live Time for Culture and Hard Questions" },
      { h2: "Our Real-World Experience at theRec" },
    ],
  },
  {
    id: "video-vs-text",
    slug: "when-to-send-video-vs-written-update",
    primaryKeyword: "async video vs text communication",
    metaTitle: "When to Send a Video vs. a Written Update",
    metaDescription: "Decision framework for async video vs text on distributed teams.",
    eeatAngle: "One-month internal message audit tagging 40% of eng updates as video-native.",
    outline: [
      { h2: "Video Wins When Context Is Visual" },
      { h2: "Text Wins When the Answer Is Factual and Short" },
      { h2: "Video Wins When Tone and Trust Matter" },
      { h2: "Text Wins When People Need to Search and Reference" },
      { h2: "Use the Rework Test Before You Record" },
      { h2: "Our Real-World Experience at theRec" },
    ],
  },
  {
    id: "remote-feedback",
    slug: "giving-clear-feedback-distributed-teams",
    primaryKeyword: "giving feedback remote teams",
    metaTitle: "How to Give Clear Feedback on Remote Teams",
    metaDescription: "Specific, timely feedback practices for distributed teams—async and live.",
    eeatAngle: "Feedback Fridays experiment and tiered Slack criticism policy at theRec.",
    outline: [
      { h2: "Be Specific About Behavior and Impact" },
      { h2: "Match the Medium to the Weight of the Message" },
      { h2: "Shorten the Loop—Feedback Decays Fast" },
      { h2: "Ask Permission Before Dropping a Heavy Message" },
      { h2: "Document Agreements, Not Just Critiques" },
      { h2: "Model Receiving Feedback Publicly" },
      { h2: "Our Real-World Experience at theRec" },
    ],
  },
  {
    id: "async-video",
    slug: "complete-guide-async-video-communication",
    primaryKeyword: "async video communication",
    metaTitle: "Complete Guide to Async Video Communication for Teams",
    metaDescription: "How async video helps distributed teams share context and reduce meetings.",
    eeatAngle: "Browser-first recording workflow designed for async handoffs at theRec.",
    outline: [
      { h2: "What Async Video Communication Means" },
      { h2: "When Async Video Beats Live Calls" },
      { h2: "Standards That Make Adoption Stick" },
      { h2: "Common Pitfalls and How to Avoid Them" },
      { h2: "Our Real-World Experience at theRec" },
    ],
  },
  {
    id: "remote-work-culture",
    slug: "building-strong-remote-work-culture",
    primaryKeyword: "remote work culture",
    metaTitle: "How to Build a Strong Remote Work Culture",
    metaDescription: "Design trust, norms, and rituals that survive time zones—not virtual happy hours.",
    eeatAngle: "Time-to-clarity metric replaced meeting count as culture KPI at theRec.",
    outline: [
      { h2: "Write Down How You Work Together" },
      { h2: "Replace Presence With Visible Progress" },
      { h2: "Invest in Rituals That Scale Async" },
      { h2: "Protect Focus Time as a Cultural Value" },
      { h2: "Measure Culture by Retention and Clarity" },
      { h2: "Our Real-World Experience at theRec" },
    ],
  },
  {
    id: "distributed-productivity",
    slug: "distributed-team-productivity-framework",
    primaryKeyword: "distributed team productivity",
    metaTitle: "Distributed Team Productivity Framework (2026 Guide)",
    metaDescription: "Priorities, async workflows, handoffs, and output metrics for distributed teams.",
    eeatAngle: "Eleven to four weekly meeting hours after async standups at theRec engineering org.",
    outline: [
      { h2: "One Source of Truth for Priorities" },
      { h2: "Separate Coordination From Creation" },
      { h2: "Async Visibility Without Surveillance" },
      { h2: "Handoffs Are Productivity Infrastructure" },
      { h2: "Measure Output, Not Activity" },
      { h2: "Our Real-World Experience at theRec" },
    ],
  },
  {
    id: "async-standups",
    slug: "async-standups-remote-teams-guide",
    primaryKeyword: "async standups remote teams",
    metaTitle: "Async Standups for Remote Teams: Complete Guide",
    metaDescription: "Templates and rules for async standups that respect time zones.",
    eeatAngle: "Mon/Wed/Fri async standups cut six meeting hours per person monthly.",
    outline: [
      { h2: "Pick a Cadence That Matches Your Sprint" },
      { h2: "Use a Fixed Template", h3: ["Done / Next / Blocked"] },
      { h2: "Set a Submission Window" },
      { h2: "Escalate Blockers Live, Not Everything" },
      { h2: "Keep a Searchable Archive" },
      { h2: "Our Real-World Experience at theRec" },
    ],
  },
  {
    id: "use-cases",
    slug: "screen-recording-use-cases-remote-teams",
    primaryKeyword: "screen recording remote teams",
    metaTitle: "Screen Recording Use Cases for Remote Teams",
    metaDescription: "Engineering, support, product, and onboarding use cases for async screen recording.",
    eeatAngle: "Cross-functional recording library reduced repeat walkthrough calls.",
    outline: [
      { h2: "Engineering and QA Bug Reproduction" },
      { h2: "Product and Design Walkthroughs" },
      { h2: "Customer Support Personalized Responses" },
      { h2: "HR and Operations Onboarding Libraries" },
      { h2: "Our Real-World Experience at theRec" },
    ],
  },
  {
    id: "recording-quality",
    slug: "professional-screen-recording-best-practices",
    primaryKeyword: "screen recording best practices",
    metaTitle: "Professional Screen Recording Best Practices",
    metaDescription: "Planning, audio, visuals, and sharing tips for credible business recordings.",
    eeatAngle: "Internal recording quality checklist used before customer-facing shares.",
    outline: [
      { h2: "Plan Before You Press Record" },
      { h2: "Prioritize Clear Audio" },
      { h2: "Reduce Visual Noise" },
      { h2: "Verify Sharing Settings Before Publish" },
      { h2: "Our Real-World Experience at theRec" },
    ],
  },
  {
    id: "screen-camera",
    slug: "screen-camera-vs-screen-only-recording",
    primaryKeyword: "screen recording with camera",
    metaTitle: "Screen + Camera vs Screen-Only Recording",
    metaDescription: "Choose the right recording mode for demos, support, and team updates.",
    eeatAngle: "Mode selection guide derived from customer demo conversion data.",
    outline: [
      { h2: "When Screen-Only Wins" },
      { h2: "When Camera + Screen Wins" },
      { h2: "When Camera-Only Wins" },
      { h2: "Match Mode to Viewer, Not Recorder" },
      { h2: "Our Real-World Experience at theRec" },
    ],
  },
  {
    id: "video-onboarding-customers",
    slug: "video-onboarding-customer-success-teams",
    primaryKeyword: "video onboarding customers",
    metaTitle: "Video Onboarding for Customer Success Teams",
    metaDescription: "Personalized video onboarding to reduce time-to-value and support tickets.",
    eeatAngle: "Video cohort activated two days faster than doc-only onboarding in A/B test.",
    outline: [
      { h2: "Map the First Seven Days" },
      { h2: "Personalize the First Touch" },
      { h2: "Build a Searchable Library" },
      { h2: "Pair Video With Measurable CTAs" },
      { h2: "Know When to Go Live" },
      { h2: "Our Real-World Experience at theRec" },
    ],
  },
  {
    id: "async-communication-etiquette",
    slug: "async-communication-etiquette-distributed-teams",
    primaryKeyword: "async communication etiquette",
    metaTitle: "Async Communication Etiquette for Distributed Teams",
    metaDescription: "Norms for async messaging, urgency, response times, and closing loops.",
    eeatAngle: "One-page etiquette doc reduced post-launch confusion tickets next sprint.",
    outline: [
      { h2: "Lead With Context and a Clear Ask" },
      { h2: "Label Urgency Explicitly" },
      { h2: "Respect Response-Time Norms" },
      { h2: "Close Loops Publicly" },
      { h2: "Choose the Right Medium" },
      { h2: "Our Real-World Experience at theRec" },
    ],
  },
];
